version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: electrobuilder-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: electrobuilder
      POSTGRES_PASSWORD: electrobuilder
      POSTGRES_DB: electrobuilder

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: